--1
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (1, N'Nendoroid Frieren', CAST(241.10 AS Decimal(10, 2)), N'Frieren: Beyond Journey''s End', 15, N'Jul 2024', N'Good Smile Company', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f1.jpg', N'~/Image/Product/f1-2.jpg')
--2
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (2, N'TENITOL Jess', CAST(233.40 AS Decimal(10, 2)), N'Butareba: The Story of a Man Turned into a Pig', 10, N'Aug 2024', N'FURYU', N'Painted plastic non-scale complete product with stand included. Height: Approximately 220mm (including stand).', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f2.jpg', N'~/Image/Product/f2-2.jpg')
--3
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (3, N'Usada Pekora', CAST(1414.90 AS Decimal(10, 2)), N'hololive production', 10, N'Aug 2024', N'FREEing', N'Painted plastic 1/4 scale complete product with stand included. Approximately 460mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f3.jpg', N'~/Image/Product/f3-2.jpg')
--4
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (4, N'Chen Hai', CAST(707.50 AS Decimal(10, 2)), N'Azur Lane', 5, N'Oct 2024', N'Good Smile Arts Shanghai', N'Painted plastic 1/7 scale complete product with stand included. Approximately 220mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f4.jpg', N'~/Image/Product/f4-2.jpg')
--5
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (5, N'Marcille Donato: Adding Color to the Dungeon', CAST(926.00 AS Decimal(10, 2)), N'Delicious in Dungeon', 5, N'Dec 2024', N'Good Smile Company', N'Painted plastic 1/7 scale complete product with stand included. Approximately 260mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f5.jpg', N'~/Image/Product/f5-2.jpg')
--6
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (6, N'Mikasa Ackerman: DX Ver. (Rerelease)', CAST(804.00 AS Decimal(10, 2)), N'Attack on Titan', 15, N'Dec 2024', N'Good Smile Company', N'ainted plastic 1/8 scale complete product with stand included. Approximately 280mm in height (including base).', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f6.jpg', N'~/Image/Product/f6-2.jpg')
--7
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (7, N'Kurige-chan', CAST(636.70 AS Decimal(10, 2)), N'Kurige Horse Original Character', 10, N'Aug 2024', N'Solarain', N'Painted plastic 1/7 scale complete product with stand included. Approximately 270mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f7.jpg', N'~/Image/Product/f7-2.jpg')
--8
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (8, N'POP UP PARADE Eren Yeager: Attack Titan Ver.', CAST(154.00 AS Decimal(10, 2)), N'Attack on Titan', 30, N'Nov 2021', N'Good Smile Company', N'Painted ABS&PVC non-scale complete product with stand included. Approximately 150mm in height.', N'Scale Figures', N'Available', N'~/Image/Product/f8.jpg', N'~/Image/Product/f8-2.jpg')
--9
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (9, N'Racing Miku 2021: Private Ver.', CAST(959.00 AS Decimal(10, 2)), N'Hatsune Miku GT Project', 5, N'Feb 2024', N'Max Factory', N'Painted plastic 1/7 scale complete product with stand included. Approximately 250mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f9.jpg', N'~/Image/Product/f9-2.jpg')
--10
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (10, N'POP UP PARADE Goblin Slayer', CAST(127.50 AS Decimal(10, 2)), N'GOBLIN SLAYER', 10, N'Sep 2019', N'Good Smile Company', N'Painted ABS&PVC non-scale complete product with stand included. Approximately 180mm in height.', N'Scale Figures', N'Available', N'~/Image/Product/f41.jpg', N'~/Image/Product/f41-2.jpg')
--11
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (11, N'Izuku Midoriya: Deku Ver.', CAST(933.50 AS Decimal(10, 2)), N'My Hero Academia', 5, N'Jul 2024', N'PROOF', N'Painted plastic complete product with base included. Includes main figure and interchangeable head part. Approximately 255mm in height.', N'Scale Figures', N'Pre-Order', N'~/Image/Product/f42.jpg', N'~/Image/Product/f42-2.jpg')
--12
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (12, N'Nendoroid Chisato Nishikigi: Cafe LycoReco Uniform Ver.', CAST(200.00 AS Decimal(10, 2)), N'Lycoris Recoil', 20, N'May 2024', N'Good Smile Company', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Pre-Order', N'~/Image/Product/f10.jpg', N'~/Image/Product/f10-2.jpg')
--13
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (13, N'Nendoroid Takina Inoue: Cafe LycoReco Uniform Ver.', CAST(200.00 AS Decimal(10, 2)), N'Lycoris Recoil', 10, N'May 2024', N'Good Smile Company', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Pre-Order', N'~/Image/Product/f11.jpg', N'~/Image/Product/f11-2.jpg')
--14
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (14, N'Nendoroid Fern', CAST(189.00 AS Decimal(10, 2)), N'Frieren: Beyond Journey''s End', 30, N'Jul 2024', N'Good Smile Company', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f12.jpg', N'~/Image/Product/f12-2.jpg')
--15
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (15, N'Nendoroid Shiroko Sunaookami', CAST(254.00 AS Decimal(10, 2)), N'Blue Archive', 15, N'Apr 2024', N'Max Factory', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Pre-Order', N'~/Image/Product/f13.jpg', N'~/Image/Product/f13-2.jpg')
--16
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (16, N'Nendoroid Shigure Ui', CAST(241.00 AS Decimal(10, 2)), N'Shigure Ui', 10, N'Jul 2023', N'Good Smile Arts Shanghai', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f14.jpg', N'~/Image/Product/f14-2.jpg')
--17
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (17, N'Nendoroid Minato Aqua', CAST(196.20 AS Decimal(10, 2)), N'hololive production', 15, N'Dec 2021', N'Good Smile Company', N'Painted ABS&PVC non-scale articulated figure with stand included. Approximately 110mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f15.jpg', N'~/Image/Product/f15-2.jpg')
--18
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (18, N'Nendoroid Cheshire', CAST(257.30 AS Decimal(10, 2)), N'Azur Lane', 10, N'Jan 2024', N'Good Smile Arts Shanghai', N'Painted plastic non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f16.jpg', N'~/Image/Product/f16-2.jpg')
--19
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (19, N'NULLShangri-La Frontier Plushie Emul', CAST(106.00 AS Decimal(10, 2)), N'Shangri-La Frontier', 10, N'Apr 2024', N'Good Smile Company', N'Material: Polyester / Size: Approx. 170mm in height (Sunraku), approx. 170mm in height including hat (Emul).', N'Dolls', N'Pre-Order', N'~/Image/Product/f17.jpg', N'~/Image/Product/f17-2.jpg')
--20
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (20, N'Shangri-La Frontier Plushie Sunraku', CAST(106.00 AS Decimal(10, 2)), N'Shangri-La Frontier', 10, N'Apr 2024', N'Good Smile Company', N'Material: Polyester / Size: Approx. 170mm in height (Sunraku), approx. 170mm in height including hat (Emul).', N'Dolls', N'Pre-Order', N'~/Image/Product/f18.jpg', N'~/Image/Product/f18-2.jpg')
--20
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (21, N'Love Live! Nijigasaki High School Idol Club Plushie Ayumu Uehara', CAST(141.50 AS Decimal(10, 2)), N'Love Live! Nijigasaki High School Idol Club', 15, N'Apr 2023', N'Good Smile Company', N'Materials: Polyester, cotton / Size: Approx. 180mm in height.
', N'Dolls', N'Available', N'~/Image/Product/f19.jpg', N'~/Image/Product/f19-2.jpg')
--21
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (22, N'Attack on Titan Cart Titan Plushie', CAST(530.60 AS Decimal(10, 2)), N'Attack on Titan', 25, N'Apr 2023', N'Good Smile Company', N'Materials: Cotton, polyester / Size: Approx. 28cm', N'Dolls', N'Available', N'~/Image/Product/f20.jpg', N'~/Image/Product/f20-2.jpg')
--22
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (23, N'Atelier Ryza: Ever Darkness & the Secret Hideout The Animation Plushie Reisalin Stout', CAST(141.50 AS Decimal(10, 2)), N'Atelier Ryza: Ever Darkness & the Secret Hideout The Animation', 10, N'Feb 2024', N'Good Smile Company', N'Materials: Polyester / Size: Approx. 170mm in height.', N'Dolls', N'Pre-Order', N'~/Image/Product/f21.jpg', N'~/Image/Product/f21-2.jpg')
--23
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (24, N'Frieren: Beyond Journey''s End Plushie Frieren', CAST(141.50 AS Decimal(10, 2)), N'TV anime "Frieren: Beyond Journey''s End"', 10, N'Apr 2024', N'Good Smile Company', N'Materials: Cotton, polyester / Size: Approx. 170mm in height.', N'Dolls', N'Pre-Order', N'~/Image/Product/f22.jpg', N'~/Image/Product/f22-2.jpg')
--24
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (25, N'Sword Art Online the Movie -Progressive- Scherzo of Deep Night Plushie Asuna', CAST(160.00 AS Decimal(10, 2)), N'Sword Art Online the Movie -Progressive- Scherzo of Deep Night', 20, N'Feb 2022', N'Good Smile Company', N'Materials: Cotton, polyester / Size: Approx. 170mm in height.', N'Dolls', N'Available', N'~/Image/Product/f23.jpg', N'~/Image/Product/f23-2.jpg')
--25
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (26, N'<SIDE MS> GUNDAM AGE-FX', CAST(634.60 AS Decimal(10, 2)), N'Mobile Suit Gundam Age', 10, N'May 2024', N'METAL ROBOT SPIRITS
', N'The AGE-FX Gundam AGE-FX is the successor to the AGE-3 Gundam AGE-3 Normal, which was introduced in the Mobile Suit Gundam AGE Three Generation Arc. It is piloted by Kio Asuno.', N'Gundam', N'Pre-Order', N'~/Image/Product/f24.jpg', N'~/Image/Product/f24-2.jpg')
--26
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (27, N'<SIDE MS> Rising Freedom Gundam', CAST(634.60 AS Decimal(10, 2)), N'Mobile Suit Gundam SEED Freedom', 30, N'January 26, 2024', N'METAL ROBOT SPIRITS', N'Is it certain destiny, or a struggle for freedom? The Rising Freedom Gundam from "Mobile Suit Gundam SEED Freedom" comes to the METAL ROBOT SPIRITS!', N'Gundam', N'Available', N'~/Image/Product/f25.jpg', N'~/Image/Product/f25-2.jpg')
--27
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (28, N'<SIDE MS> Immortal Justice Gundam
', CAST(634.60 AS Decimal(10, 2)), N'Mobile Suit Gundam SEED Freedom', 30, N'
February 17, 2024', N'METAL ROBOT SPIRITS', N'Is it predetermined destiny, or a struggle for freedom? The Immortal Justice Gundam from "Mobile Suit Gundam SEED Freedom" joins METAL ROBOT SPIRITS!', N'Gundam', N'Available', N'~/Image/Product/f26.jpg', N'~/Image/Product/f26-2.jpg')
--28
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (29, N'＜SIDE MS＞BUSTER GUNDAM ver.A.N.I.M.E.', CAST(370.20 AS Decimal(10, 2)), N'Mobile Suit Gundam SEED', 5, N'July 2024', N'METAL ROBOT SPIRITS', N'ROBOT SPIRITS ver. A.N.I.M.E. Buster Gundam" appears in "Mobile Suit Gundam Seed"! Finally, the initial five Gundam models are all here. item has many highlights, such as the gimmick of connecting the two large guns that are connected by an arm from the main body of the MS and a wealth of effects!', N'Gundam', N'Pre-Order', N'~/Image/Product/f27.jpg', N'~/Image/Product/f27-2.jpg')
--29
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (30, N'AILE STRIKER -STORE LIMITED EDITION-', CAST(32.00 AS Decimal(10, 2)), N'Mobile Suit Gundam SEED', 30, N'January 18, 2024', N'METAL ROBOT SPIRITS', N'The unique structure proposed by mechanical designer Kunio Okawara allows for various expressions that completely change the image of the conventional Aile Strike. Not only can it be attached to the "METAL BUILD Strike Gundam" series (sold separately), but it also comes with a special backpack that allows you to attach the Striker Pack to the "METAL BUILD Gundam Astray" series (sold separately), allowing you to enjoy various variations.', N'Gundam', N'Available', N'~/Image/Product/f28.jpg', N'~/Image/Product/f28-2.jpg')
--30
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (31, N'<SIDE MS> Gundam Barbatos (1st to 4th forms)', CAST(634.60 AS Decimal(10, 2)), N'Mobile Suit Gundam: Iron-Blooded Orphans', 10, N'June 2024', N'METAL ROBOT SPIRITS', N'The interwoven diecast frame with detailed painting and a weighty feel recreates the weapon’s realism. Furthermore, it is possible to convert from the 1st form to the 4th form with the wide variety of accessories provided. The smoothbore gun can be switched from stored state to shelling state without any replacements by using the built-in transformation mechanism. Gundam Barbatos is created with thorough pursuit of modeling, materials, coloring, and gimmicks.
', N'Gundam', N'Pre-Order', N'~/Image/Product/f29.jpg', N'~/Image/Product/f29-2.jpg')
--31
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (32, N'Pop Team Epic T-Shirt： Pipimi Fire S/M/L', CAST(100.00 AS Decimal(10, 2)), N'Pop Team Epic Season 2', 10, N'May 2024', N'GoodSmile Moment', N'Material： 100% Cotton', N'Goods', N'Pre-Order', N'~/Image/Product/f30.jpg', N'~/Image/Product/f30-2.jpg')
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (33, N'A-Z:[B] Tech Jacket (Free)', CAST(225.00 AS Decimal(10, 2)), N'A-Z:', 40, N'Feb 2024', N'Good Smile Company', N'Material: 100% polyester Size: Length (snaps to hem): approx. 73cm, width: approx. 66cm, Shoulder: approx. 62cm, Sleeve length: approx. 55cm, Armhole: approx. 26.5cm', N'Goods', N'Available', N'~/Image/Product/f31.jpg', N'~/Image/Product/f31-2.jpg')
--32
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (34, N'The Apothecary Diaries Plushie Maomao', CAST(100.00 AS Decimal(10, 2)), N'The Apothecary Diaries', 35, N'Feb 2024', N'Good Smile Company', N'Materials: Polyester / Size: Approx. 150mm in height.', N'Goods', N'Available', N'~/Image/Product/f32.jpg', N'~/Image/Product/f32-2.jpg')
--33
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (35, N'Pop Team Epic Guruguru Plushie Keychain Popuko', CAST(50.00 AS Decimal(10, 2)), N'Pop Team Epic Season 2', 10, N'May 2024', N'GoodSmile Moment', N'Material: Polyester, PVC, alloy / Size: Head: Approx. W8.4cm x H6.5 cm (Including hair: Approx. W14cm)
', N'Goods', N'Pre-Order', N'~/Image/Product/f33.jpg', N'~/Image/Product/f33-2.jpg')
--34
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (36, N'Burnish Flare Necklace', CAST(100.00 AS Decimal(10, 2)), N'PROMARE', 20, N'Apr 2024', N'ORANGE ROUGE FLUFFY LAND', N'Materials: Brass, Epoxy Resin / Size: Charm Size: Approx. 32mm', N'Goods', N'Pre-Order', N'~/Image/Product/f34.jpg', N'~/Image/Product/f34-2.jpg')
--35
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (37, N'FLUFFY LAND Plushie Keychain River', CAST(50.00 AS Decimal(10, 2)), N'FLUFFY LAND', 10, N'Apr 2024', N'GoodSmile Moment', N'Material: polyester, alloy; Size: head: approx. 10.5cm in length, 12.5 cm in width. Tail: approx. 8.5 cm in length, 5 cm in width.', N'Goods', N'Pre-Order', N'~/Image/Product/f35.jpg', N'~/Image/Product/f35-2.jpg')
--36
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (38, N'Cyberpunk: Edgerunners Plushie Rebecca', CAST(123.00 AS Decimal(10, 2)), N'Cyberpunk: Edgerunners', 20, N'Jun 2023', N'Good Smile Company', N'Materials: Cotton, polyester / Size: Approx. 130mm in height.', N'Dolls', N'Available', N'~/Image/Product/f36.jpg', N'~/Image/Product/f36-2.jpg')
--37
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (39, N'Chainsaw Man Plushie Aki Hayakawa', CAST(125.00 AS Decimal(10, 2)), N'Chainsaw Man', 25, N'Aug 2023', N'Good Smile Company', N'Material: Cotton, polyester / SizeMaterials: Polyester / Size: Approx. H400mm x W550mm x D190mm : H130Material: Cotton, polyester / Size: H130mm', N'Dolls', N'Available', N'~/Image/Product/f37.jpg', N'~/Image/Product/f37-2.jpg')
--38
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (40, N'Hatsune Miku NT Big Plushie', CAST(230.00 AS Decimal(10, 2)), N'Piapro Characters', 30, N'Jul 2023', N'Good Smile Company', N'Materials: Polyester / Size: Approx. H400mm x W550mm x D190mm', N'Dolls', N'Available', N'~/Image/Product/f38.jpg', N'~/Image/Product/f38-2.jpg')
--39
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (41, N'Nendoroid Saitama', CAST(75.00 AS Decimal(10, 2)), N'ONE-PUNCH MAN', 15, N'Dec 2019', N'Good Smile Company', N'Painted ABS&PVC non-scale articulated figure with stand included. Approximately 100mm in height.', N'Nendoroids', N'Available', N'~/Image/Product/f39.jpg', N'~/Image/Product/f39-2.jpg')
--40
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (42, N'Nendoroid Bond Forger', CAST(128.00 AS Decimal(10, 2)), N'SPY x FAMILY', 40, N'May 2024', N'Good Smile Company', N'Painted ABS&PVC non-scale articulated figure with stand included.', N'Nendoroids', N'Available', N'~/Image/Product/f40.jpg', N'~/Image/Product/f40-2.jpg')
--41
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (43, N'＜SIDE MS＞MD-0032G GUEL’S DILANZA ver. A.N.I.M.E.', CAST(335.00 AS Decimal(10, 2)), N'Mobile Suit Gundam: The Witch from Mercury', 15, N'June 2024', N'METAL ROBOT SPIRITS', N'The "Diranza Gweru Special Machine" ridden by Gweru Jetak is now available at ROBOT SPIRITS ver. A.N.I.M.E.!', N'Gundam', N'Pre-Order', N'~/Image/Product/f43.jpg', N'~/Image/Product/f43-2.jpg')
--42
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (44, N'<SIDE MS> FREEDOM GUNDAM (Real Type Color)', CAST(582.00 AS Decimal(10, 2)), N'Mobile Suit Gundam SEED', 30, N'January 2024', N'METAL ROBOT SPIRITS', N'METAL ROBOT SPIRITS FREEDOM GUNDAM is now available in real type color! Reproduce detailed color coding and markings. Commercialized as a finished product model that further pursues reality as a weapon!', N'Gundam', N'Available', N'~/Image/Product/f44.jpg', N'~/Image/Product/f44-2.jpg')
--43
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (45, N'＜SIDE MS＞RX-178 GUNDAM Mk-Ⅱ (TITANS) ver. A.N.I.M.E.', CAST(265.00 AS Decimal(10, 2)), N'Mobile Suit Ζeta Gundam', 30, N'April 2024', N'METAL ROBOT SPIRITS', N'ROBOT SPIRITS ver. A.N.I.M.E. Finally, the "Mobile Suit Zeta Gundam" series has begun. The first model is the Gundam Mk-II, the "Black Gundam" that symbolizes the power of the Titans!', N'Gundam', N'Available', N'~/Image/Product/f45.jpg', N'~/Image/Product/f45-2.jpg')
--44
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (46, N'<SIDE MS> GUNDAM TR-1 [HAZEL CUSTOM] (COMBAT DEPLOYMENT COLORS) ＆ OPTION PARTS SET', CAST(582.00 AS Decimal(10, 2)), N'Advance of Zeta: The Flag of Titans', 30, N'April 2024', N'METAL ROBOT SPIRITS', N'METAL ROBOT SPIRITS FREEDOM GUNDAM is now available in real type color! Reproduce detailed color coding and markings. Commercialized as a finished product model that further pursues reality as a weapon!', N'Gundam', N'Available', N'~/Image/Product/f46.jpg', N'~/Image/Product/f46-2.jpg')
--45
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (47, N'Blue Archive Chihiro''s Millennium Science School Varsity Jacket', CAST(185.00 AS Decimal(10, 2)), N'Blue Archive', 5, N'May 2024', N'Good Smile Company', N'Material - Outer lining: 100% polyester / Inner lining: 100% polyester / Rib knit trim: 85% cotton, 13% polyester, 2% polyurethane / Size - Length: approx. 71cm, width: approx. 67cm, shoulder width: approx. 55cm, sleeve length: approx. 62cm', N'Goods', N'Pre-Order', N'~/Image/Product/f47.jpg', N'~/Image/Product/f47-2.jpg')
--46
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (48, N'Fate/Grand Order Metal Charm Collection Sword of Rupture Ea', CAST(167.00 AS Decimal(10, 2)), N'Fate/Grand Order', 15, N'Apr 2023', N'Good Smile Company', N'Materials: Brass. Size: Approx. 11cm in length.', N'Goods', N'Available', N'~/Image/Product/f48.jpg', N'~/Image/Product/f48-2.jpg')
--47
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (49, N'Fate/Grand Order Metal Charm Collection Shuten-Douji''s Sword', CAST(167.00 AS Decimal(10, 2)), N'Fate/Grand Order', 15, N'Apr 2023', N'Good Smile Company', N'Materials: Brass. Size: Approx. 13cm in length.', N'Goods', N'Available', N'~/Image/Product/f49.jpg', N'~/Image/Product/f49-2.jpg')
--48
INSERT INTO [dbo].[Figure] ([FigureID], [FigureName], [FigurePrice], [FigureSeries], [FigureUnit], [FigureReleaseDate], [FigureManufacturer], [FigureSpecification], [FigureCategory], [FigureStatus], [FigureImage1], [FigureImage2]) VALUES (50, N'Sesame Street Nendoroid Plus Acrylic Keychains Elmo', CAST(30.00 AS Decimal(10, 2)), N'Sesame Street', 30, N'Jan 2023', N'Good Smile Company', N'Materials: Acrylic. Size: Approx. 60mm', N'Goods', N'Available', N'~/Image/Product/f50.jpg', N'~/Image/Product/f50-2.jpg')
